services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: force-market-frontend-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
